# Generated by Django 2.1.7 on 2019-05-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hEntrada', models.TimeField(verbose_name='Configuração de Horario (Entrada)')),
                ('hSaida', models.TimeField(verbose_name='Configuração de Horario (Saída)')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=128, verbose_name='Nome de usuário blog')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome Completo')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('data_de_nascimento', models.CharField(blank=True, max_length=128, null=True, verbose_name='Data de nascimento')),
                ('chefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario', verbose_name='AAA')),
                ('confHora', models.ManyToManyField(to='frequencia.ConfHorario', verbose_name='Horarios')),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario')),
            ],
        ),
    ]
