# Generated by Django 2.1.7 on 2019-05-18 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('hEntrada', models.TimeField(verbose_name='Configuração de Horario (Entrada)')),
                ('hSaida', models.TimeField(verbose_name='Configuração de Horario (Saída)')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=128, verbose_name='Nome de usuário')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome Completo')),
                ('data_de_nascimento', models.CharField(blank=True, max_length=128, null=True, verbose_name='Data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Ponto',
            fields=[
                ('entrada', models.DateTimeField(auto_now_add=True, verbose_name='Entrada')),
                ('saida', models.DateTimeField(auto_now_add=True, verbose_name='Saída')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ip do Funcionario')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frequencia.Funcionario')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Status', verbose_name='Status do Funcionário')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
            },
        ),
        migrations.AddField(
            model_name='justificativa',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='chefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario', verbose_name='Superior'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='confHora',
            field=models.ManyToManyField(to='frequencia.ConfHorario', verbose_name='Horarios'),
        ),
    ]
