# Generated by Django 2.1.7 on 2019-05-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
    ]
