# Generated by Django 2.2.1 on 2019-05-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0002_auto_20190519_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_ponto',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
