# Generated by Django 2.2.1 on 2019-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0003_registro_ponto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_ponto',
            name='entrada',
            field=models.TimeField(verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='saida',
            field=models.TimeField(verbose_name='Saída'),
        ),
    ]
