# Generated by Django 2.2.1 on 2019-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0004_auto_20190519_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_ponto',
            name='entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída'),
        ),
    ]
